version: '3.8'
services:
db:
image: mysql:8.0
environment:
MYSQL_ROOT_PASSWORD: root
MYSQL_DATABASE: tdshop
ports:
- '3306:3306'
volumes:
- db_data:/var/lib/mysql


mailhog:
image: mailhog/mailhog
ports:
- '1025:1025' # SMTP
- '8025:8025' # Web UI


push-emulator:
build: ./push-emulator
ports:
- '3000:3000'
depends_on:
- db


volumes:
db_data: